### ISSUE TITLE
custom avro schema

### ISSUE THREAD

**Issue by hishamag-student** [data-burst/debezium_avro_integration#19]
I want to add a custom avro schema for this table for example: create table test (id serial primary key, salary numeric)
I tried this {
  "type": "record",
  "name": "test",
  "namespace": "public",
  "fields": [
    {"name": "id", "type": "int", "default": 0},
    {"name": "salary", "type": "double", "default": 0.00}
  ]
}

how to use this?

**Comment by mostafaghadimi** [comment]
@hishamag-student You have to create a connector. Check the Debezium documentation. 
https://debezium.io/documentation/
